### ISSUE TITLE
Add command for redirecting to documentation site

### ISSUE THREAD

**Issue by arifszn** [chkware/vscode-ext#27]
![image](https://user-images.githubusercontent.com/45073703/188570053-15a45d53-07c5-4006-b501-d3f4bc416c23.png)

Add a new command for redirecting to the documentation site. So that it won't feel like there is only one command available. Thoughts?

**Comment by 0hsn** [comment]
- becomes irrelevant when we implement #29 
- however I feel necessity of shortcut for going to website's example page for a relevant document. but, I'll think about it later.

**Comment by 0hsn** [comment]
@arifszn let's implement this regardless, guess this is a good issue to solve now.
