### ISSUE TITLE
Change summary in marketplace

### ISSUE THREAD

**Issue by arifszn** [chkware/vscode-ext#28]
Currently, the summary is too long when it is viewed from the extension tab. It can be simple text like `Helper for chkware`. Then later can be `Linter for chkware` (when the linter is available).

<img width="960" alt="image" src="https://user-images.githubusercontent.com/45073703/188571111-7ca98541-bb4d-42c6-b4a6-bcc88850b2e7.png">

Also, the homepage should be the docs site instead of the GitHub repository.

![image](https://user-images.githubusercontent.com/45073703/188572018-6a68ff0f-c517-4648-82d4-78f9ec3a899e.png)

**Comment by 0hsn** [comment]
- I found that it supports 41 chars on standard screen size. Therefore I suggest summary to be `Write and execute chkware spec files`.
- Homepage don't seem a problem to me

@arifszn
