### ISSUE TITLE
Show `reload required` after uninstall

### ISSUE THREAD

**Issue by 0hsn** [chkware/vscode-ext#43]
A force reload is needed after uninstall the extension. It is required at this point to just show a `reload required` after the extension been uninstalled.

fyi: I have seen some extension those don't need reload (or they do it inherently, but user don't realize)

**Comment by arifszn** [comment]
I am not sure what the requirement is. Currently after uninstalling the released version, `reload required` is shown like this. 

![image](https://user-images.githubusercontent.com/45073703/216759150-43926741-5d25-4389-9368-10ce34e2490c.png)

**Comment by 0hsn** [comment]
It didn't for me that instance, so I was unsure whether we were supposed to add something. You can mark this issue resolved now. Thanks!

**Comment by arifszn** [comment]
I think vscode decides internally if it needs to be reloaded.
